### ISSUE TITLE
Add documentation build and publish in package.json

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#18]
Get inspired

https://github.com/image-js/core/blob/d166bd5a0e6b493097c9feefd1ca7bf3903052c4/package.json#L37-L38

**Comment by lpatiny** [comment]
This should also lead to the suppression of documentation.md

**Comment by lpatiny** [comment]
In the dev-dependencies you may use the head of documentation.js

https://github.com/image-js/core/blob/d166bd5a0e6b493097c9feefd1ca7bf3903052c4/package.json#L65

**Comment by maasencioh** [comment]
@lpatiny why don't use `cheminfo doc` instead for the docs generation?

**Comment by lpatiny** [comment]
Indeed it will do the job.

So if you want to build and publish you should simply install the cheminfo-tools npm

`npm install cheminfo-tools -g`

And then 

`cheminfo doc -p`

However I would expect it is available then on:

https://cheminfo-js.github.io/spectra-data

But this does not work. What I should do more ?

**Comment by maasencioh** [comment]
It's better to install the tools as global with `npm install cheminfo-tools -g`, but after it's generated the docs dir, you need to enable the pages from settings, I can't do this in this repo for permissions but [here you have a post](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)

**Comment by lpatiny** [comment]
Thanks Miguel. I updated my comment to add the '-g'. GH-pages Works perfectly. There is just some work to have the correct jsdoc format now ...
