### ISSUE TITLE
Write correctly the documentation

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#19]
The syntax of jsdoc is quite strict ...

http://usejsdoc.org/

You may get inspired from: (should remove `@memberof` and `@instance` that are specific to image-js)
https://github.com/image-js/core/blob/d166bd5a0e6b493097c9feefd1ca7bf3903052c4/src/image/transform/grey.js#L5-L26

**Comment by andcastillo** [comment]
@lpatiny  Can we close this?
