### ISSUE TITLE
jsdoc documentation

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#28]
Currently there is some documentation in the code but it is not written in the correct format.

You may get inspired by : https://github.com/image-js/core/blob/master/src/image/transform/grey.js

However in this case 
 * @memberof Image
 * @instance
is probably not required because documentation-js can figure out by itself it is a method of the associated class.

**Comment by stropitek** [comment]
See also #52

**Comment by andcastillo** [comment]
Can we close this? The documentation is correct now?

**Comment by andcastillo** [comment]
@stropitek  @lpatiny ?
