### ISSUE TITLE
Find a way to specify the reference in the spectrum

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#29]
In the peak picking view and compare we should be able to shift the spectrum

**Comment by andcastillo** [comment]
there is a function SD.shift(value) that shift the given spectrum in the x axis. You can also shift in the y axis with SD.yShift(value).
@lpatiny  does it works? Perhaps we just need to keep the value inside to revert the action.

**Comment by lpatiny** [comment]
I never tried this function but it looks like it could solve our problems. @stropitek do you think we could click with the tracking mode on a spectrum and have the value of this peak that is editable ?

Concerning storing the shift I think it would be important in the case of jcamp generation. @andcastillo do you know how to store this correctly in the jcamp without having to invent a parameter ? But yes this shift should be kept somewhere in SD in order to be able to write the jcamp. SD should also deal with reference for 2D spectra.

**Comment by andcastillo** [comment]
there is a parameter OFFSET added by bruker to shift in thge x dimension. And it does what you need.
