### ISSUE TITLE
Would be better to make push / join(CRLF)

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#35]
https://github.com/cheminfo-js/spectra-data/blob/c3578a2/src/jcampEncoder/JcampCreator.js#L17

**Comment by andcastillo** [comment]
I don't understand @lpatiny

**Comment by lpatiny** [comment]
You could use a structure like:

var result=[];
result.push('my first string');
result.push('my second string');
return result.join(CRLF);

**Comment by andcastillo** [comment]
When I did that function I checked and the advise was to use direct concatenation instead of the array push. It was faster at that time.

**Comment by lpatiny** [comment]
OK well possible this. We suggested this because the code looks prettier (at our point of view) but I will make a jsperf to check this.
For sure the push used to be faster but you are probably right that this changed with time.

**Comment by andcastillo** [comment]
I definitely could not find anything concluding about this.  A benchmark would help. @targos know something about it?

**Comment by lpatiny** [comment]
Yes you are right the concat is faster than the join currently with chrome:
https://jsperf.com/test-push-or-concat
So you may leave it like that.

**Comment by lpatiny** [comment]
Same result on Safari:
![image](https://cloud.githubusercontent.com/assets/1484241/20629065/de7a8c64-b329-11e6-82c5-26807aced801.png)
