### ISSUE TITLE
Better to have function XXX than var XXX=function

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#39]
https://github.com/cheminfo-js/spectra-data/blob/e92167314d912e1ddd57169fb2d3f9d9b5110ff5/src/jcampEncoder/VectorEncoder.js#L66

**Comment by andcastillo** [comment]
I'll try to fix those old thing everywhere. By now I've fixed it in the code you hint

**Comment by lpatiny** [comment]
You could make a query by regular expressions in order to find all the '= function'

**Comment by andcastillo** [comment]
I did. But, what if I directly export the function?
`module.exports.myFunction = function (var1, opts) `
Did you say something about to create a named function and export it after?
@targos @lpatiny

**Comment by targos** [comment]
> say something about to create a named function and export it after?

That's what I usually do but you can also write `module.exports.myFunction = function myfunction(){}`
