### ISSUE TITLE
super() is implicit in constructor

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/spectra-data#42]
This code is useless

https://github.com/cheminfo-js/spectra-data/blob/master/src/NMR.js#L18

**Comment by andcastillo** [comment]
It seems that super() is not implicit. Webstorm complains if if I have a empty constructor.  On the other hand I don't want to overload the constructor, so I don't need to define it. It will inherit from the super.

**Comment by lpatiny** [comment]
@targos  Any comments on this ?

**Comment by targos** [comment]
The constructor itself is implicit (with call to super) as @andcastillo pointed out.
