### ISSUE TITLE
Separate peakPicking from Range creation

### ISSUE THREAD

**Issue by stropitek** [cheminfo-js/spectra-data#46]
We should probably separate the part that calculates the peaks from the part that creates ranges for NMR from it. The peak calculation would be a method of SD while the range calculation is a method of NMR. @andcastillo could that easily be done?

**Comment by andcastillo** [comment]
That has sence

**Comment by andcastillo** [comment]
@stropitek check and let me know

**Comment by stropitek** [comment]
Seems ok after fixing some issues e208ac8fe46372b489d996a4b50059fba6991730
