### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stropitek** [cheminfo-js/spectra-data#51]
I've updated the documentation link to point to the documentation built with `cheminfo doc`

Can we remove the old documentation [`Documentation.md`](https://github.com/cheminfo-js/spectra-data/blob/master/Documentation.md) ?

**Comment by lpatiny** [comment]
Daniel could you prepare the same system ad we have for image-js where we build the documentation in gh-pages. It will be agood motivation to write correctly the docs !

**Comment by stropitek** [comment]
Yes that's what the `cheminfo doc` command does

**Comment by lpatiny** [comment]
It is is not done yet just publish in gh-pages the current state of the docs and add the link on spectra-data

**Comment by stropitek** [comment]
It does not need to be in gh-pages, but in `./docs`
[here](https://cheminfo-js.github.com/spectra-data/)

**Comment by andcastillo** [comment]
You can delete the Documentation.md. It was generated automatically too.
