### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by andcastillo** [cheminfo-js/spectra-data#54]
@stropitek why the automatic eslint fix produce these extra whites in before and after the curly? Is it the expected format?
```
if (sub % 2 === 0)                            {
   outString += '(X++(R..R)), XYDATA' + CRLF;
}                                                  else                                   {
                        outString += '(X++(I..I)), XYDATA' + CRLF;
}
```

**Comment by maasencioh** [comment]
that's the fix that the do, and there's no eslint rule to avoid that many spaces, so currently I'm only able to fix if by hand

**Comment by targos** [comment]
If that's what they do I think you should open an issue in the ESLint project (look if there is already one) because this fix violates our indentation rule

**Comment by maasencioh** [comment]
@targos but that's not related with identation, that's the problem, that currently there's no rule to caught this issue (as far as I know)

**Comment by targos** [comment]
The line 4 of this example has an indentation problem.

**Comment by targos** [comment]
If that appeared with ESLint-fix then it's a bug with ESLint because fixes are not supposed to introduce errors with other rules

**Comment by targos** [comment]
I'd like to see the original code before you run ESLint-fix

**Comment by maasencioh** [comment]
it's the same but without the braces

**Comment by targos** [comment]
There is a rule. It's called [no-multi-spaces](http://eslint.org/docs/rules/no-multi-spaces), it is auto-fixable and I added it to our common configuration.

**Comment by targos** [comment]
BTW the full list of ESLint rules is available here: http://eslint.org/docs/rules/
If you realize that we should add or change one of them, please open an issue in our custom config repo: https://github.com/cheminfo/eslint-config
